names = [ "Beck's (non-alcoholic)",
"Budweiser America",
"Bud Light",
"Bud Light Platinum",
"Corona Extra",
"Hoegaarden",
"Michelob Ultra",
"Shock Top - Raspberry Wheat",
"Shock Top - Twisted Pretzel Wheat",
"Stella Artois",
"Budweiser America",
"Bud Light",
"Busch Beer",
"Busch Beer (16oz)",
"Natural Light",
"Bud America",
"Bud Ice",
"Bud Light"
]
